// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file CamImage.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "CamImage.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

CamImage::CamImage()
{
    m_value = 0;


}

CamImage::~CamImage()
{
}

CamImage::CamImage(const CamImage &x)
{
    m_value = x.m_value;
}

CamImage::CamImage(CamImage &&x)
{
    m_value = x.m_value;
}

CamImage& CamImage::operator=(const CamImage &x)
{
    m_value = x.m_value;

    return *this;
}

CamImage& CamImage::operator=(CamImage &&x)
{
    m_value = x.m_value;

    return *this;
}

size_t CamImage::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t CamImage::getCdrSerializedSize(const CamImage& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void CamImage::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_value;
}

void CamImage::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_value;
}

size_t CamImage::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            

    return current_align;
}

bool CamImage::isKeyDefined()
{
    return false;
}

void CamImage::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
}